Support test of shapefile contents, quite system out and expected warnings
geotools/geotools pull request #3284
Opened 2020-12-22 22:30 UTC by jodygarnett

This is a non functional change improving testing.

# Checklist

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/geotools/geotools/blob/master/CONTRIBUTING.md)
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.
- [x] The changes are not breaking the build in downstream projects using SNAPSHOT dependencies, GeoWebCache and GeoServer (there is an automatic PR check verifying this, check this when it turns green).

The following are required only for core and extension modules (they are welcomed, but not required, for unsupported modules):

- [ ] There is an issue in [Jira](https://osgeo-org.atlassian.net/projects/GEOT) describing the bug/task/new feature (a notable exemptions is, changes not visible to end users). The ticket is for the GeoTools project, if the issue was found elsewhere it's a good practice to link to the origin ticket/issue.
- [ ] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message(s) must be in the form "[GEOT-XYZW] Title of the Jira ticket"
- [ ] New unit tests have been added covering the changes
- [x] This PR passes all existing unit tests (test results will be reported by Continuous Integration after opening this PR)
- [x] This PR passes the [QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html) (QA checks results will be reported by Continuous Integration after opening this PR)
- [ ] Documentation has been updated accordingly.

Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or not applicable.

2020-12-22 22:31 UTC, jodygarnett commented
@jnh5y was using this to test XYZM regression for JTS 1.18 release, you can use it to confirm fix...

2020-12-23 08:42 UTC, aaime commented
There is already a bunch of tests for XYZ, XYM and XYZM cases in the shapefile store (some of them added just recenlty). Can you elaborate on what type of extra coverages are these new tests providing?

2020-12-23 14:20 UTC, jnh5y commented
@aaime good question!  The existing test use shapefiles to check for exact binary matches.  

With the new JTS version, the only thing which failed is the orientation of the MultiPolygonZM here: https://github.com/geotools/geotools/blob/master/modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShapefileDataStoreTest.java#L2091-L2094.

I found that switching the order of two middle coordinates fixed the test.  Jody is proposing this change to check the contents of the shapefiles instead of checking the bytes on disk.

2021-02-01 09:36 UTC, aaime requested changes
In addition to the other comments, the QA build failed due to deprecated API usage:

```
2020-12-22T22:45:25.6835912Z [WARNING] /home/runner/work/geotools/geotools/modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShapefileDataStoreTest.java:[2113,77] toURL() in java.io.File has been deprecated
```

2021-02-01 09:36 UTC, aaime commented on modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/TestCaseSupport.java
> +import static org.junit.Assert.*;
No wildcard imports please (there is a QA rule to prevent it, but was not running for tests, so far... the PMD support for tests just landed)

2021-02-01 09:36 UTC, aaime commented on modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShapefileDataStoreTest.java
> +        ShapefileDataStore referenceDS = new ShapefileDataStore(expectedFile.toURL());
Please use ``URLs.toURL(file)`` here

2021-05-17 09:05 UTC, aaime commented
Closing, the PR has been open for serveral months and reviewer's feedback ignored in the meantime.

2021-05-17 09:05 UTC, closed without merging