[GEOT-7030] Missing YSLD support for rule vendor options
geotools/geotools pull request #3694
Opened 2021-11-30 22:27 UTC by sikeoka

This PR updates the YSLD style format to handle vendor options for rules.

  

# Checklist

- [X] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [X] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [X] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [X] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [X] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [X] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [X] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [X] Bug fixes and small new features are presented as a single commit.
- [X] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

2021-12-01 08:18 UTC, aaime commented
@jodygarnett this one is up your alley I think.
@sikeoka lots of test failures:

```
2021-11-30T22:37:20.2920205Z [ERROR] Errors: 
2021-11-30T22:37:20.2923170Z [ERROR]   SldTransformerTest.testPointSimple:53->transform:2039 » Emitter expected NodeE...
2021-11-30T22:37:20.2931934Z [ERROR]   SldTransformerTest.testPointWithAttribute:337->transform:2039 » Emitter expect...
2021-11-30T22:37:20.2934009Z [ERROR]   SldTransformerTest.testPointWithGraphic:130->transform:2039 » Emitter expected...
2021-11-30T22:37:20.2935745Z [ERROR]   SldTransformerTest.testPointWithLabel:461->transform:2039 » Emitter expected N...
2021-11-30T22:37:20.2937398Z [ERROR]   SldTransformerTest.testPointWithLegend:176->transform:2039 » Emitter expected ...
2021-11-30T22:37:20.2939212Z [ERROR]   SldTransformerTest.testPointWithRotatedLabel:593->transform:2039 » Emitter exp...
2021-11-30T22:37:20.2941021Z [ERROR]   SldTransformerTest.testPointWithRotation:373->transform:2039 » Emitter expecte...
2021-11-30T22:37:20.2942881Z [ERROR]   SldTransformerTest.testPointWithRuleVendorOption:640->transform:2039 » Emitter
2021-11-30T22:37:20.2948827Z [ERROR]   SldTransformerTest.testPointWithScale:246->transform:2039 » Emitter expected N...
2021-11-30T22:37:20.2954948Z [ERROR]   SldTransformerTest.testPointWithStroke:90->transform:2039 » Emitter expected N...
2021-11-30T22:37:20.2956778Z [ERROR]   SldTransformerTest.testPointWithStyledLabel:521->transform:2039 » Emitter expe...
2021-11-30T22:37:20.2958800Z [ERROR]   SldTransformerTest.testPointWithTransparentTriangle:412->transform:2039 » Emitter
2021-11-30T22:37:20.2959957Z [INFO] 
```

2021-12-01 17:52 UTC, sikeoka commented
I had a mistake in the original commit but it's fixed now.

2021-12-28 22:46 UTC, sikeoka commented
If there's no one to review this module can this just be merged if everything passes?

2021-12-29 08:02 UTC, aaime commented
If there is no one to review we should consider calling the module unmaintained and pushing it down to unsupported land (or find a new maintainer). @jodygarnett I thought you had an interest in the module?

2021-12-31 07:32 UTC, jodygarnett commented
Excellent, I was wanting see this improvement made.

2021-12-31 07:37 UTC, jodygarnett commented on modules/extension/ysld/src/test/java/org/geotools/ysld/encode/YsldEncodeCookbookTest.java
> +        // </UserStyle>
Do we really need the commended out sld here?

2021-12-31 07:39 UTC, jodygarnett commented on modules/extension/ysld/src/test/java/org/geotools/ysld/parse/YsldParseCookbookTest.java
> +        // </UserStyle>
The cookbook tests are here to ensure the examples from the documentation work as advertised, so one fix is to add this to the cookbook.

2021-12-31 07:42 UTC, jodygarnett requested changes
Thanks for the clean addition, to complete this I would like to complete the doc checklist for the ylsd page https://docs.geotools.org/latest/userguide/extension/ysld.html

2021-12-31 07:53 UTC, jodygarnett commented
I added the documentaiton change, when the builds have completed I will rebase this PR. Thanks again for the contribution.

2021-12-31 07:53 UTC, jodygarnett approved these changes

2022-01-05 15:56 UTC, jodygarnett commented
It is failing in docs:
```
/home/runner/work/geotools/geotools/docs/user/tutorial/datastore/strategy.rst:245:Could not lex literal_block as "java". Highlighting skipped.
```

Appears unrelated.

2022-01-05 16:49 UTC, aaime commented
It is unrelated, see this other PR for an analysis and a solution (if you want to get green builds, you can try to rebase this one, or merge with main):
https://github.com/geotools/geotools/pull/3724#issuecomment-1003533144

2022-01-05 17:01 UTC, jodygarnett commented
Thanks, I rebased with main locally have pushed up the changes after local testing.

2022-01-05 17:02 UTC, closed without merging

2022-01-05 22:48 UTC, jodygarnett commented
Thanks for the fix @sikeoka I have backported to 26.x, let me know if you need it backported to 25.x.