[GEOT-7131] Clarify ImageMosaic documentation with an example
geotools/geotools pull request #3868
Opened 2022-04-30 06:47 UTC by roarbra

Added a small program to display an Image Mosaic. One of the features being multi-threading. During that process there were some issues that caused me to add exception handling and logging.

# Checklist

- [X] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [X] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [X] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [X] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [X] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [X] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [X] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [X] Bug fixes and small new features are presented as a single commit.
- [X] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

2022-05-02 10:19 UTC, aaime requested changes
Looks ok to me, added a suggestion to align logging with the rest of the library (tip, logs don't ask themselves questions, they state a situation instead).

2022-05-02 10:19 UTC, aaime commented on modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/MosaicQueryBuilder.java
> +                    "Are we using multithreading? isMultithreadingAllowed: "
```suggestion
                    "Multithreading status: "
```

2022-05-03 07:06 UTC, aaime commented
Fails due to package lookup issues, [fix is here](https://github.com/geotools/geotools/pull/3871), rebase when merged.

2022-05-06 13:01 UTC, mprins approved these changes

2022-05-06 13:02 UTC, merged