[GEOT-7064] H2GIS 2.0.0
geotools/geotools pull request #3917
Opened 2022-06-02 10:48 UTC by ebocher

This PR proposes to add a new method on SQLDialect to retrieve a java type when the static mapping fails.
This PR is related to the issue [GEOT-7064](https://osgeo-org.atlassian.net/browse/GEOT-7064).

Feel free to comments.

# Checklist

- [ ] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement]
- [ ] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [ ] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [ ] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

2022-06-03 14:23 UTC, ebocher commented
Note : 
I'm not able to add a unit test with this PR because the new geometry signature is related to the last H2 database (2.x version) and GT uses a very old one. 
However, this fix is used and tested here https://github.com/orbisgis/h2gis-geotools/pull/40

2022-06-06 09:16 UTC, aaime requested changes

2022-06-06 09:16 UTC, aaime commented on modules/library/jdbc/src/main/java/org/geotools/jdbc/SQLDialect.java
> +    public Class<?> getDesiredColumnMapping(String sqlTypeName) {
I'd just be more concise, and aligned with the naming already available in JDBCDataStore.

```suggestion
    public Class<?> getMapping(String sqlTypeName) {
```

2022-06-06 12:09 UTC, aaime approved these changes

2022-06-06 12:09 UTC, merged

2022-06-06 12:09 UTC, aaime commented
squash-merged on main, as 4a0c88c