[GEOT-7210] YSLD styles do not set the layer name
geotools/geotools pull request #4000
Opened 2022-08-30 15:23 UTC by sikeoka

This PR updates the YSLD parser to set the name of the NamedLayer so that YSLD styles can be used with GeoServer's WMS dynamic styling.  The style name was unnecessarily being set twice.

  

# Checklist

- [ ] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [ ] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [ ] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [ ] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

2022-09-06 16:00 UTC, sikeoka commented
@jodygarnett could you review this when you have time since you reviewed my last YSLD PR?

2022-09-19 15:09 UTC, sikeoka commented
Any thoughts on this PR @aaime or @jodygarnett?

2022-10-04 14:58 UTC, sikeoka commented
Any thoughts on this PR @jodygarnett?

2022-10-11 15:30 UTC, sikeoka commented
Any thoughts on this PR @jodygarnett?

2022-10-15 18:13 UTC, jodygarnett commented
@sikeoka thanks; sorry to take so long to get back to this. I have been so focused feedback from the geoserver 2.22-M0 that I am only just looking around the rest of the codebase.

2022-10-15 19:25 UTC, jodygarnett commented
Okay so what we have is a one to one mapping from root elements to user style.

May I provide an idea that is in keeping with the rest of the YSLD approach?
- one to one mapping always
- squash levels together if they are redundant; using prefix to clarify 

Option 1: Define new root elements using layer prefix

- `layer-name` maps to user layer

Option 2: Start to define SLD wrappers formally

Just like you can parse line symbolizes isolation (and it will assume the rest)

```
line:
  stroke-width: 1.0
  stroke-color: '#99cc00'
```

Treat the existing root elements as a user style (with SLD named layer and style layer descriptor assumed)

If you see `user-styles:` then parse out a named layer
```
name: roads_layer
user styles:
- name: road_style
  title: Road Style
  feature-styles:
  - name: casing
    rules:
    - symbolizers:
      - line:
          stroke-color: black
          stroke-width: 5px
  - name: linework
    rules:
    - symbolizers:
      - line:
          stroke-color: '#8080E6'
          stroke-width: 3px
```

2022-10-15 19:29 UTC, jodygarnett requested changes
YSLD does not offer mapping for SLD concepts at present; please see comments for discussion (it would be a good feature to add).

2022-10-17 16:20 UTC, sikeoka commented on modules/extension/ysld/src/main/java/org/geotools/ysld/parse/RootParser.java
> +        layer.setName(root.str("name"));
I updated it to use "layer-name" for the layer name.

2022-10-18 05:47 UTC, jodygarnett approved these changes

2022-10-18 05:49 UTC, jodygarnett reviewed
I see the value being parsed; but not written out. 

Many of the other tests do a round trip to ensure what is written out can be parsed without change.

2022-10-18 05:56 UTC, merged