[GEOT-7307] Calling getSchema on GeoJSONDataStore gives NullPointerEcxception
geotools/geotools pull request #4193
Opened 2023-02-10 14:33 UTC by roarbra

Make sure typeName is set before using it.

# Checklist

- [X] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [X] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [X] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [X] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [X] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [X] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [X] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [X] Bug fixes and small new features are presented as a single commit.
- [X] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

2023-02-10 14:51 UTC, mprins commented
Assuming you added `empty.json` irt. the discussion in https://sourceforge.net/p/geotools/mailman/geotools-gt2-users/thread/CAHkAV%2BS72d1CSBhe%3Dj6VhmNhu%2BrG17EJg1_d0fJSvsVGNQr22g%40mail.gmail.com/#msg37774724

2023-02-10 14:52 UTC, mprins approved these changes

2023-02-13 14:05 UTC, roarbra commented
Rebase seemed to work.

2023-02-13 22:42 UTC, jodygarnett requested changes
This class should not be caching values alongside ContentEntry. 

If additional state is needed make a subclass of GeoJSONContentEntry subclass of ContentEntry.

2023-02-14 07:11 UTC, roarbra commented on modules/unsupported/geojson-store/src/main/java/org/geotools/data/geojson/store/GeoJSONDataStore.java
> +            }
@jodygarnett This PR tries to cover up for the NullPointerException. Not for the faulty implementation.

2023-03-13 19:32 UTC, closed without merging