[GEOT-7361] Support non EPSG authorities in DataUtilities type spec, and property data store
geotools/geotools pull request #4292
Opened 2023-05-19 16:58 UTC by aaime

Allow property data store to use the IAU authority, and other authorities, in support for non EPSG authority code development and test (as the property store is our favourite test data store).

# Checklist

- [ ] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [ ] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [ ] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [ ] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

2023-05-20 01:13 UTC, jodygarnett commented on modules/library/main/src/main/java/org/geotools/data/DataUtilities.java
> +     *       <li><code>authority=<#></code>
```suggestion
     *       <li><code>authority=text</code>
```

2023-05-20 01:14 UTC, jodygarnett commented on modules/library/main/src/main/java/org/geotools/data/DataUtilities.java
>       *       <li><code>srid=<#></code>
```suggestion
     *       <li><code>srid=number</code>
```

2023-05-20 01:15 UTC, jodygarnett commented on modules/library/main/src/main/java/org/geotools/data/DataUtilities.java
> +     *     EPSG (the default): "*point:Point:authority=IAUsrid=49900"
```suggestion
     *     EPSG (the default): "*point:Point:authority=IAU:srid=49900"
```

2023-05-20 01:17 UTC, jodygarnett requested changes
Some minor doc changes

2023-05-22 09:58 UTC, aaime commented
All suggested changes applied, thanks @jodygarnett 
Merging.

2023-05-22 09:59 UTC, merged