[GEOT-7451] Upgrade org.json:json to 20230618
geotools/geotools pull request #4487
Opened 2023-09-23 12:15 UTC by turingtestfail

# Checklist

- [ ] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [ ] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [ ] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [ ] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

2023-09-23 12:29 UTC, mprins requested changes

2023-09-23 12:29 UTC, mprins commented on modules/unsupported/flatgeobuf/pom.xml
> +            <version>220230618</version>
There appears to be a typo here

2023-09-23 12:42 UTC, turingtestfail commented on modules/unsupported/flatgeobuf/pom.xml
> +            <version>220230618</version>
Fixed

2023-09-24 09:47 UTC, mprins approved these changes

2023-09-24 09:48 UTC, mprins commented
there does not seem to be a relation to the failing mapfish print; that looks like a dependency fetching issue in gradle

2023-09-24 09:48 UTC, merged

2023-09-24 09:55 UTC, mprins commented
@turingtestfail you may need to create a manual backport for 30.x; as 30-RC was already tagged and released. I've added the "backport 30.x" label but the bot does not seem to pick that up after merge..

2023-09-24 10:01 UTC, aaime commented
The backport to `30.x` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
To https://github.com/geotools/geotools.git
 ! [rejected]              backport-4487-to-30.x -> backport-4487-to-30.x (non-fast-forward)
error: failed to push some refs to 'https://github.com/geotools/geotools.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. If you want to integrate the remote changes,
hint: use 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

```
</details>


To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-30.x 30.x
# Navigate to the new working tree
cd .worktrees/backport-30.x
# Create a new branch
git switch --create backport-4487-to-30.x
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick 2820bcd1bc2d1fd3a731eca81f30e1724d2b31b9
# Push it to GitHub
git push --set-upstream origin backport-4487-to-30.x
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-30.x
```
Then, create a pull request where the `base` branch is `30.x` and the `compare`/`head` branch is `backport-4487-to-30.x`.

2023-09-24 10:01 UTC, aaime commented
The backport to `28.x` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
To https://github.com/geotools/geotools.git
 ! [rejected]              backport-4487-to-28.x -> backport-4487-to-28.x (non-fast-forward)
error: failed to push some refs to 'https://github.com/geotools/geotools.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. If you want to integrate the remote changes,
hint: use 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

```
</details>


To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-28.x 28.x
# Navigate to the new working tree
cd .worktrees/backport-28.x
# Create a new branch
git switch --create backport-4487-to-28.x
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick 2820bcd1bc2d1fd3a731eca81f30e1724d2b31b9
# Push it to GitHub
git push --set-upstream origin backport-4487-to-28.x
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-28.x
```
Then, create a pull request where the `base` branch is `28.x` and the `compare`/`head` branch is `backport-4487-to-28.x`.