CQL2 - implements the Abstract TestSuite (ATS) conformance testsuite
geotools/geotools pull request #4983
Opened 2024-11-13 10:19 UTC by pmauduit

See https://github.com/geoserver/geoserver-ogcapi/issues/10 for the motivation. This PR mainly provides a transcription of the OGC Abstract Test Suite to Java test classes for both cql2 modules (text & json).

It also reflects some changes from the specifications, e.g. renaming ENVELOPE to BBOX in the filters.

# Checklist

- [ ] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [ ] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [ ] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [ ] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

2024-11-13 16:06 UTC, aaime requested changes
Great job @pmauduit, I left a few comments below.

2024-11-13 16:06 UTC, aaime commented on modules/unsupported/cql2-json/src/test/java/org/geotools/filter/text/cqljson/conformance/ConformanceTest17OnlineTest.java
> +public class ConformanceTest17OnlineTest extends ATSOnlineTest {
Shouldn't it extend ConformanceTest17OnlineTest ?

2024-11-13 16:06 UTC, aaime commented on modules/unsupported/cql2-json/src/test/java/org/geotools/filter/text/cqljson/conformance/ConformanceTest17OnlineTest.java
> +    public static Collection<Object[]> params() {
Eventually the explanations could be centralized in one place... dunno, the ConformanceUtils class for example. And just point there any time filter references are missing.

2024-11-13 16:06 UTC, aaime commented on modules/unsupported/cql2-json/src/test/java/org/geotools/filter/text/cqljson/conformance/ConformanceTest23OnlineTest.java
> +        return Arrays.asList(
See ConformanceTest17OnlineTest comments

2024-11-13 16:06 UTC, aaime commented on modules/unsupported/cql2-json/src/test/java/org/geotools/filter/text/cqljson/conformance/ConformanceTest42OnlineTest.java
> +                    /* {"{}", 1}, // TODO broken text filter, cannot be converted to json
See ConformanceTest17OnlineTest comments

2024-11-13 16:06 UTC, aaime commented on pom.xml
> +          <environmentVariables>
I would add a clarifying comment as to why the env variable is set

2024-11-14 10:23 UTC, pmauduit commented
thanks for the feedback, PR updated consequently

2024-11-14 11:48 UTC, merged